"""create_world_tables

Revision ID: 1f1344a2017f
Revises: b9d9a1747d9b
Create Date: 2026-07-10 00:26:16.110901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f1344a2017f'
down_revision: Union[str, None] = 'b9d9a1747d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biomes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biomes_name'), 'biomes', ['name'], unique=True)
    op.create_table('regions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_room_id'), 'regions', ['room_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=True),
    sa.Column('biome_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('biome', sa.String(length=50), nullable=False),
    sa.Column('connected_locations', sa.JSON(), nullable=False),
    sa.Column('npc_list', sa.JSON(), nullable=False),
    sa.Column('monster_list', sa.JSON(), nullable=False),
    sa.Column('loot_table', sa.JSON(), nullable=False),
    sa.Column('weather', sa.String(length=50), nullable=False),
    sa.Column('danger_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['biome_id'], ['biomes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_biome_id'), 'locations', ['biome_id'], unique=False)
    op.create_index(op.f('ix_locations_region_id'), 'locations', ['region_id'], unique=False)
    op.create_index(op.f('ix_locations_room_id'), 'locations', ['room_id'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('npc_list', sa.JSON(), nullable=False),
    sa.Column('inventory', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_location_id'), 'buildings', ['location_id'], unique=False)
    op.create_table('objects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objects_location_id'), 'objects', ['location_id'], unique=False)
    op.add_column('game_states', sa.Column('current_location_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'game_states', 'locations', ['current_location_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_states', type_='foreignkey')
    op.drop_column('game_states', 'current_location_id')
    op.drop_index(op.f('ix_objects_location_id'), table_name='objects')
    op.drop_table('objects')
    op.drop_index(op.f('ix_buildings_location_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_locations_room_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_region_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_biome_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_regions_room_id'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_biomes_name'), table_name='biomes')
    op.drop_table('biomes')
    # ### end Alembic commands ###
