"""index_game_states_location_id

Revision ID: 8c06e256ed21
Revises: b6893b15bcdb
Create Date: 2026-07-10 00:45:11.531828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c06e256ed21'
down_revision: Union[str, None] = 'b6893b15bcdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_game_states_current_location_id'), 'game_states', ['current_location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_states_current_location_id'), table_name='game_states')
    # ### end Alembic commands ###
