"""create_npc_tables

Revision ID: b6893b15bcdb
Revises: 1f1344a2017f
Create Date: 2026-07-10 00:37:37.059274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6893b15bcdb'
down_revision: Union[str, None] = '1f1344a2017f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('npcs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('race', sa.String(length=50), nullable=False),
    sa.Column('profession', sa.String(length=50), nullable=False),
    sa.Column('personality', sa.String(length=255), nullable=False),
    sa.Column('mood', sa.String(length=50), nullable=False),
    sa.Column('inventory', sa.JSON(), nullable=False),
    sa.Column('relationships', sa.JSON(), nullable=False),
    sa.Column('daily_schedule', sa.String(length=255), nullable=False),
    sa.Column('goals', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npcs_location_id'), 'npcs', ['location_id'], unique=False)
    op.create_index(op.f('ix_npcs_room_id'), 'npcs', ['room_id'], unique=False)
    op.create_table('npc_memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('npc_id', sa.Uuid(), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('player_message', sa.String(length=512), nullable=False),
    sa.Column('npc_response', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npc_memories_npc_id'), 'npc_memories', ['npc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_npc_memories_npc_id'), table_name='npc_memories')
    op.drop_table('npc_memories')
    op.drop_index(op.f('ix_npcs_room_id'), table_name='npcs')
    op.drop_index(op.f('ix_npcs_location_id'), table_name='npcs')
    op.drop_table('npcs')
    # ### end Alembic commands ###
