"""create_game_tables

Revision ID: b9d9a1747d9b
Revises: aed4a54fe948
Create Date: 2026-07-10 00:01:03.718323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d9a1747d9b'
down_revision: Union[str, None] = 'aed4a54fe948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_events_room_id'), 'game_events', ['room_id'], unique=False)
    op.create_table('game_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('current_location', sa.String(length=100), nullable=False),
    sa.Column('current_time', sa.String(length=50), nullable=False),
    sa.Column('weather', sa.String(length=50), nullable=False),
    sa.Column('current_quest', sa.String(length=255), nullable=False),
    sa.Column('active_npcs', sa.JSON(), nullable=False),
    sa.Column('active_monsters', sa.JSON(), nullable=False),
    sa.Column('objects', sa.JSON(), nullable=False),
    sa.Column('inventory', sa.JSON(), nullable=False),
    sa.Column('world_flags', sa.JSON(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('turn_stage', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_states_room_id'), 'game_states', ['room_id'], unique=True)
    op.create_table('player_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action_text', sa.String(length=255), nullable=False),
    sa.Column('resolved_status', sa.String(length=50), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_actions_room_id'), 'player_actions', ['room_id'], unique=False)
    op.create_index(op.f('ix_player_actions_user_id'), 'player_actions', ['user_id'], unique=False)
    op.create_table('story_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('entry_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_history_room_id'), 'story_history', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_history_room_id'), table_name='story_history')
    op.drop_table('story_history')
    op.drop_index(op.f('ix_player_actions_user_id'), table_name='player_actions')
    op.drop_index(op.f('ix_player_actions_room_id'), table_name='player_actions')
    op.drop_table('player_actions')
    op.drop_index(op.f('ix_game_states_room_id'), table_name='game_states')
    op.drop_table('game_states')
    op.drop_index(op.f('ix_game_events_room_id'), table_name='game_events')
    op.drop_table('game_events')
    # ### end Alembic commands ###
